name: Test

on:
  pull_request:
    branches:
      - main  # Set a branch name to trigger deployment
  workflow_call:
    
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn test