name: Test

on:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn test